### ISSUE TITLE
Customer Statement print out for all customers

### ISSUE THREAD

**Issue by alikoyakp** [consoleerp/janin_erpnext#1]
Please make customer / supplier statement as attached.
[Customer Statement for all Customers.pdf](https://github.com/consoleerp/janin_erpnext/files/855279/Customer.Statement.for.all.Customers.pdf)

**Comment by fahimalizain** [comment]
I read about Customer Statement, and understood that it is a statement given to the customer regarding the pending payments for transactions done.

- Is this solely dependent on Sales Invoice ?
   I saw a sample customer statement `sql` query and saw that he is using Sales Invoice only.
   What if there is any other mode of cash by the customer ? Like advanced payments ?

- There are two ways to do this :
   - A normal ERPNext Report
      - Report can be seen in the ERPNext itself
      - You will have to filter each customer and click print
   - A JasperReport
      - Report can be seen in Print Preview
      - I can print separate Customer Statements for each customer in a single click.

Pls confirm to start development.
